### ISSUE TITLE
Type Error when filtering a Quantity Value from a Classification Store 

### ISSUE THREAD

**Issue by robertSt7** [pimcore/admin-ui-classic-bundle#610]
- Create an Object with a Classification Store with a Quantity Value in it
- Open the grid 
- Add the Quantity Value and try to filter

`	
Timestamp: Fri Jul 12 2024 11:09:43 GMT+0200 (Central European Summer Time)
Status: 500 | Internal Server Error
URL: /admin/object/grid-proxy?classId=6&folderId=1189&xaction=read&_dc=1720775383720
Method: POST
Message: Pimcore\Db\Helper::escapeLike(): Argument #1 ($like) must be of type string, array given, called in /var/www/html/dev/pimcore/pimcore/models/DataObject/ClassDefinition/Data.php on line 460
Trace: 
in /var/www/html/dev/pimcore/pimcore/lib/Db/Helper.php:108
#0 /var/www/html/dev/pimcore/pimcore/models/DataObject/ClassDefinition/Data.php(460): Pimcore\Db\Helper::escapeLike(Array)
#1 [internal function]: Pimcore\Model\DataObject\ClassDefinition\Data->Pimcore\Model\DataObject\ClassDefinition\{closure}(Array)
#2 /var/www/html/dev/pimcore/pimcore/models/DataObject/ClassDefinition/Data.php(459): array_map(Object(Closure), Array)
#3 /var/www/html/dev/pimcore/admin-ui-classic-bundle/src/Helper/GridHelperService.php(124): Pimcore\Model\DataObject\ClassDefinition\Data->getFilterConditionExt(Array, '=', Array)
#4 /var/www/html/dev/pimcore/admin-ui-classic-bundle/src/Helper/GridHelperService.php(646): Pimcore\Bundle\AdminBundle\Helper\GridHelperService->getFeatureAndSlugFilters('[{"operator":"g...', Object(Pimcore\Model\DataObject\ClassDefinition), 'en')
#5 /var/www/html/dev/pimcore/admin-ui-classic-bundle/src/Controller/Admin/DataObject/DataObjectActionsTrait.php(105): Pimcore\Bundle\AdminBundle\Helper\GridHelperService->prepareListingForGrid(Array, 'en', Object(Pimcore\Model\User))
#6 /var/www/html/dev/pimcore/admin-ui-classic-bundle/src/Controller/Admin/DataObject/DataObjectController.php(1717): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->gridProxy(Array, 'object', Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher), Object(Pimcore\Bundle\AdminBundle\Helper\GridHelperService), Object(Pimcore\Localization\LocaleService))
#7 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(181): Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectController->gridProxyAction(Object(Symfony\Component\HttpFoundation\Request), Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher), Object(Pimcore\Bundle\AdminBundle\Helper\GridHelperService), Object(Pimcore\Localization\LocaleService), Object(Pimcore\Bundle\AdminBundle\Security\CsrfProtectionHandler))
#8 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#9 /var/www/html/vendor/symfony/http-kernel/Kernel.php(197): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#10 /var/www/html/vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php(35): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#11 /var/www/html/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
#12 /var/www/html/public/index.php(20): require_once('/var/www/html/v...')
#13 {main}
`

**Comment by kingjia90** [comment]
Closing as resolved, it was same as https://pimcore.atlassian.net/browse/PEES-674
